version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      UToRipaVTWL8z0Zw/qv6c2sd8sqIyKSCrR+dmDDOAiQmNB2uXZTN7D6Xp8O5dX97OGOTpRCDWFmPeGP5r1ykZzzFMCKVOt/8N1kYl08j7r/CxjsreU7WVfclpylJa0mW/ozE/+XDJRnNxw7WZenhIk53h7PqAP2bdAfizPqzWUfvfXI2pfXjY4lR+slwEl3RqewA6UJcxfueJhPCsTXapGE0UbRNRcB5YbltSIlYYRmA192wO2Ravt1I0AObOnXXKd0zCgrDwk22GWen3N6cifqMzcnVPjUSEf+5NlJhS4OXXqXNrVhQodYW7DUi/IS50tfCah1C4Ceube157IwstEbQxP+VPfKEX7dPR5fBcNZ7YP1MrWdTSPeojLFOPdIXZ3E6qsWf3PtbPiVHhmDTslvuEIFaiJDbxyyJEr0QvN2NUvuHvwdOQHdhA3LCuKupEYrxrX58GhUjLnTApxAZZGXfg/ffy0NzDMCUeze2yEiiIJbKazXKlh8JVUbvCJC6iua9Im7Ucw6g1n6UVvO9U6H8Yxu3HXxrnjBMhYEjoE3OUy9PRrdq7gLMwuVN/TsoTF8B7+inAoV7fYPKYXqFs7b78mbz7B+RN6stMceUfVD8HF+2U5RYz+yq+esqupfNtlpmeqi1knSXTXoac/fs+1bTKQoqBQefsSznK5WKNHE=
